spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/forall_test?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: 1234
    hikari:
      idleTimeout: 500
      connectionTimeout: 15000

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      database: mysql

server:
  port: 8080
  servlet:
    contextPath: /

coolsms:
  api:
    key: NCSVXDQ0JANEY4K3
    secret: OUSJ8FIFCYPI5WL8O8IDLA73CZSVJS7J